/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Player {
  id?: number;
  name?: string;
  passwordHash?: string;
  refreshToken?: string;
  refreshTokenExpiryTime?: string;
  userEmail?: string;
  createdAt?: string;
}

