/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { QuizQuestion } from './quizQuestion';


export interface Quiz { 
    id?: number;
    quizName?: string;
    description?: string;
    category?: Category;
    questions?: Array<QuizQuestion>;
}

