/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Quiz } from './quiz';


export interface QuizQuestion { 
    id?: number;
    questionText?: string;
    options?: Array<string>;
    correctAnswer?: string;
    difficulty?: number;
    quiz?: Quiz;
    numberOfOptions?: number;
}

