/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizSession } from './quizSession';
import { QuizQuestion } from './quizQuestion';


export interface QuizAnswer { 
    id?: number;
    question?: QuizQuestion;
    answer?: string;
    correct?: boolean;
    session?: QuizSession;
}

