/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Player } from './player';
import { Quiz } from './quiz';


export interface QuizSession { 
    id?: number;
    player?: Player;
    quiz?: Quiz;
    startTime?: number;
    totalTime?: number;
    totalScore?: number;
    questionIndex?: number;
}

