/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TriviaQuestion { 
    category?: string;
    id?: string;
    tags?: Array<string>;
    difficulty?: string;
    regions?: Array<string>;
    correctAnswer?: string;
    incorrectAnswers?: Array<string>;
    type?: string;
    question?: string;
    niche?: boolean;
}

